name: Check for Title Tag in index.html

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run title tag check
        run: |
          chmod +x ./check-title.sh
          ./check-title.sh
